import { Footer } from "@/components/common/footer";
import { Navigation } from "@/components/common/navigation";
import { ThemeProvider } from "@/components/providers/theme-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col grow max-w-6xl mx-auto w-full">
            <header className="flex justify-between items-center py-6 px-6 md:px-8">
              <Link href="/" className="group flex items-center gap-2">
                <span className="text-xl font-bold tracking-tight hidden sm:inline-block">
                  Portfolio
                </span>
              </Link>
              <Navigation />
            </header>
            <main className="grow px-6 md:px-8 relative">{children}</main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
